os: linux
jobs:
  include:
  
  - language: rust
    rust: 1.36.0
    script:
      - cd ./guidance/rust_code
      - cargo build
      - cargo test

  - language: c
    install: 
      - wget https://github.com/cgreen-devs/cgreen/releases/download/1.2.0/cgreen_1.2.0_amd64.deb -P ~/Downloads
      - sudo dpkg -i ~/Downloads/cgreen_1.2.0_amd64.deb
    compiler: gcc
    script: 
      - cd ./control
      - make test
      - cd ../navigation
      - make test
