os: linux
jobs:
  include:
  
  - language: rust
    rust: 1.36.0
    script:
      - cd ./guidance/rust_code
      - cargo build
      - cargo test

  - language: c
    install: make
    compiler: gcc
    script: 
      - cd ./control
      - make
